### ISSUE TITLE
python converts attributes to floating point

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#11]
Say you want to use a sample attribute like `replicate` in the input filename.

So you have, for example, these files:

hela_1.fastq.gz
hela_2.fastq.gz

And your annotation sheet says:

| name | replicate | cell_type |
| --- | --- | --- |
| sample1 | 1 | hela |
| sample2 | 2 | hela |

Id like to say the input file could bea derived column made by concatenating the replicate and cell_type columns, like this: `/path/to/input/{cell_type}_{replicate}.fastq.gz`

But the problem is, Python reads the `replicate` column as a floating point number and changes it to `1.0` and `2.0` by default, so it says:

`Input file does not exist or cannot be read: /path/to/input/hela_1.0.fastq.gz`

I think when we read in an annotation sheet, we should take everything verbatim (in other words, everything should be considered a string).

@afrendeiro what do you think? you've thought about this before.

**Comment by afrendeiro** [comment]
In that case, in fact, all values would be integers.

Observe the following:

```python
In [1]: import pandas as pd
In [2]: pd.Series(range(3))
Out[2]: 
0    0
1    1
2    2
dtype: int64  # type int - all fine

In [3]: pd.Series(range(3) + [pd.np.nan])
Out[3]: 
0    0.0
1    1.0
2    2.0
3    NaN
dtype: float64  # type float
```
So, when there are mixed types, Numpy (in the back of pandas) converts to float to accomodate all values in the series. See for example (non extensively) http://pandas.pydata.org/pandas-docs/stable/gotchas.html#support-for-integer-na.

I think there are two solutions:

1. the user uses quotes non-numerical values in the annotation sheet:
    ```python
    In [4]: pd.Series([str(x) for x in range(3)] + [pd.np.nan])
# equivalent to: pd.Series(["0", "1", "2", pd.np.nan])
Out[4]: 
0      0
1      1
2      2
3    NaN
dtype: object
```

2. we convert (or read in) all values in the annotation sheet to dtype `object`:
    ```python
In [5]: pd.Series(range(3) + [pd.np.nan], dtype=np.object)
Out[5]:
0      0
1      1
2      2
3    NaN
dtype: object
    ```
This last option is probably better because it does not rely on the user, but poses problems with serialization. Maybe I can test if our current serialization methods can handle this.

In the meanwhile, to have numerical characters interpreted as non-numerical, quote your values.

**Comment by nsheff** [comment]
Yep. I'm not an expert with pandas/numpy yet, but isn't there a string type (or character vector)? See http://docs.scipy.org/doc/numpy/reference/generated/numpy.chararray.html Can't we just read everything in as a chararray? chararray shouldn't have any problems being serialized.

The quote solution should work in the short term, but you're right that we should really solve this on the code side so the user doesn't have to worry about attributes getting changed on them.

these to stackoverflow questions are relevant:

http://stackoverflow.com/questions/13293810
http://stackoverflow.com/questions/13293810/

**Comment by nsheff** [comment]
See also
[models.py line 551](https://github.com/epigen/looper/blob/44a4de1224c898e3578401c69f20e36cbaff511f/looper/models.py#L551-L558)
```
		# Enforce type attributes as int
		attributes = ["lane"]
		for attr in attributes:
			if hasattr(self, attr):
				try:
					setattr(self, attr, int(getattr(self, attr)))
				except:
					pass
```

**Comment by nsheff** [comment]
The quote method doesn't seem to work...

it is still converting to floating point...

**Comment by nsheff** [comment]
FYI: In addition, openoffice calc silently converts them back into quoteless integers, so it makes the annotation sheet uneditable by openoffice.

**Comment by nsheff** [comment]
@afrendeiro do you think you can take a look at this one before we merge? this continues to bite me...

**Comment by afrendeiro** [comment]
Yes, I will try solving this once and for all.

**Comment by afrendeiro** [comment]
Okay, I believe this is now fixed (as requested).
To me this wasn't so much a "real" bug since the behaviour was as expected if you know how pandas handles mixed types, but obviously since we intent this to be broadly used I understand the need to have a value evaluated exactly as given by the user.

Now a warning:
The values retrieved from the sample objects will always be of type `str`. (Reminder: if no value is given in the annotation sheet for a certain sample, that attribute is not set in that sample.) So, beware.

This means that for example comparisons with wrong type will be False:
```python
selected_samples = [s for s in prj.samples if s.lane == 2]  # "2" here is an `int` but would be a `str` in the sample attribute
len(selected_samples)
# 0
```


In addition to my first commit (3dbffddba1f1d1c66f243c8dc945f10d498266fa), I have also removed the previous code that was a workaround to this problem (2b94ed0de65f6a7419ae0c0a5d6e166e14a54426). Please test/see if the behaviour is as desired. Happy looping :repeat:

**Comment by nsheff** [comment]
Does this correctly handle merge tables? It looks like my merge table is reading integers as `numpy.int64` instead of string.
