### ISSUE TITLE
simplifying project config

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#12]
Hi, I'm starting to think about the user experience with looper (for people who aren't developing pipelines but just using it). I think now might be a good chance to rethink and simplify the project config file. especially in light of our recent conversation about keeping things simple. I think the project config could have some things as sensible defaults that don't even need to be included, unless you want.

i think there should be a very minimal require base set.

some specific ideas:
- paths.results_subdir and paths.submission_subdir could have defaults, so they don't have to be specified in the simplest case. this change would be backward compatible
- metadata: merge_table and compare_table can be empty.
- now in simplest case, paths can have 2 elemetns and metadata only 1. should we merge these into a single block? I would put "paths" into "metadata" and elminate the paths section.
- genomes and transcriptomes should not be required any more (some pipelines may not use these)

**Comment by afrendeiro** [comment]
Correct me if I'm wrong but I think points 1 and 2 are already implemented. 

Those variables are commonly included in configs so that we show *there is the possibility* to change them (I personally do) - which brings back the theme of simple docs: we probably should present a minimal functioning config initially ([here I guess](http://looper.readthedocs.io/en/latest/inputs.html#project-config-file)), and then expand on all the configurable sections later in a dedicated page (maybe a section of Advanced features).
This would make the "Required Inputs" page smaller and less scary.

I have no objection to your third point, but this would break backward compatibility.

For the last part, I've just edited that (203b2f1).

**Comment by nsheff** [comment]
Thanks.

> Correct me if I'm wrong but I think points 1 and 2 are already implemented. 

I will double-check... I thought they could be "null" but not necessarily missing.

>we probably should present a minimal functioning config initially, and then expand on all the configurable sections later in a dedicated page 

Yes, this is exactly what I was thinking. to reduce barrier to entry.

> I have no objection to your third point, but this would break backward compatibility.

Is that OK for a new major release? Everyone with projects would have to just merge `paths` into `metadata` (not a huge fix). Or we can keep `paths` as a synonym that gets merged with `metadata` so it's optional, retaining backwards compatibility.

thanks!

**Comment by afrendeiro** [comment]
Just confirmed the first two (see [here](https://github.com/epigen/looper/blob/master/looper/models.py#L244)).

Fine with merging paths and metadata into metadata in next release. Other opinions/objections?

**Comment by nsheff** [comment]
Ok perfect. I'll start working on a minimal project config for the introduction. I think we need both a minimal example, and a comprehensive example.

I'll wait for other comments on the merging of paths/metadata for now.

**Comment by nsheff** [comment]
Since nobody seems to have strong feelings on merging paths/metadata, do you think it's safe to merge them? With backwards-compatibility, so `metadata` will just be standard, and anything in `paths` will get added to `metadata` ? Then looper will just use metadata. Any objections?

**Comment by afrendeiro** [comment]
This seems resolved and was more or less overlapping with #17, closing
