### ISSUE TITLE
Feature request: interactive logging

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#131]
Can we have a way to turn on the logger with a single function, when using interactive projects?

Motivated by #129

**Comment by vreuter** [comment]
There's `setup_looper_logger` in the package `__init__` that could do this I think. It's what's called by the main `looper` module and by the tests to configure logging. The only *required* argument is a logging level; the optionals are location(s) (to supplement the default `stdout`) and the `devmode` boolean (off by default), which triggers the switch to the message format with more information.

The required argument to `level` must be specified in the `logging` way, either as one of the level names or as a positive int (i.e., the translation from the `verbosity` way happens in `looper` CLI option interpretation rather than in this function).

Will that work, or are there changes that should be made to that function?

**Comment by nsheff** [comment]
Is the interactive logging implementation complete? I couldn't find it in the docs, but I think you did something, can you merge changes into `dev`?

**Comment by nsheff** [comment]
Hi @vreuter I'm looking for this again and can't find docs anywhere on how to do this... they may have gotten lost in the move to mkdocs? I'm not sure

But what I want to do is: in an interactive session, change peppy's logger output level to debug. I tried this:

```
In [21]: import logging                                                                                                            
In [22]: _LOGGER = logging.getLogger("peppy")                                                                                      
In [23]: _LOGGER.setLevel("DEBUG")                                                                                                 
In [24]: p2 = peppy.Project("/home/ns5bc/code/dura_macs/metadata/config.yaml", subproject="atac")                                  
Loading divvy config file: /nm/t1/databio/pepenv/uva_rivanna.yaml
Activating compute package 'default'
```
But it doesn't display debug output... can you (re) document how to do this somewhere? Sorry if I missed it

**Comment by nsheff** [comment]
I got it to work with:

```
import logmuse
_LOGGER = logmuse.setup_logger(name="peppy", level="DEBUG")
```

Maybe this should be documented in logmuse then?

**Comment by nsheff** [comment]
What confused me I think is that I thought the logger would be alread set up and I should use `setLevel` on an existing logger, with `setup` for calling a new one in a package.

**Comment by vreuter** [comment]
It's considered poor practice to configure logging in a library rather than application, because it can make it difficult for end users to control messaging. Since this is more of a library now with `looper` as the application, we don't setup logging automatically.

**Comment by vreuter** [comment]
That said, there's a `_devtools` module in `looper` that maybe has something in line with what you're looking for? That could migrate to a general `databio` and/or `pepkit` shared utils, among other things.
