### ISSUE TITLE
Proposal: eliminate Sample's knowledge of its Project

### ISSUE THREAD

**Issue by vreuter** [epigen/looper#136]
It feels perhaps too big to tackle in 0.6, or at least unnecessary, but the need for a `Sample` to have knowledge of its `Project` feels slightly strange. Quite possibly, though, there's substantial benefit to this that I don't realize since my primary interaction with `Project` and `Sample` has been one-sided and over a shorter timeframe than others'. So this may ultimately be closed with little or no change, but I wanted to track this thought that's arisen a couple of times as I've been looking at other things.

**Comment by nsheff** [comment]
we have thought about this before. there was a reason we made samples project-aware, but I don't recall at the moment.

I didn't feel it was too big of an issue because we just include a simple pointer, it's not delicately intertwined...

I don't see any advantage to making the link one-way instead of two-way, as samples will only ever belong to 1 project...

**Comment by vreuter** [comment]
There's no "just" or "simple"; it's all over the place.

**Comment by vreuter** [comment]
Advantage of not doing it is to eliminate circularity and minimize complexity.

**Comment by nsheff** [comment]
ok, then I'm sure it can be simplified.
