### ISSUE TITLE
Feature request: Detail reason for failure in _failed.flag file

### ISSUE THREAD

**Issue by rcorces** [epigen/looper#140]
If possible, it would be useful for the _failed.flag file to detail the reason for failure. For example, if a job is killed by SIGTERM or SIGKILL this job would be a good candidate for immediate re-run. This could be a job that went over-time on a cluster or (at least on our cluster) a job that was superseded. You could then have the option through looper to selectively restart jobs with a specific failure reason. Apologies if there is already a way to monitor this - I didnt find it in the docs.

**Comment by nsheff** [comment]
No, there's no way to do this (short of looking in the log files), but this is a good idea. Something I've thought about before but haven't really figured out the best way to do it. For this to work the values in the flag file would have to be standardized. what options would you propose to have in there? 

SIGINT
SIGKILL

... what else?

**Comment by rcorces** [comment]
I emailed the Sherlock staff about this. Their reply is below. Preemption
on Sherlock is basically SIGTEM/SIGKILL followed by re-initiating the job.
For looper, my understanding is that this would not work because the job
would have a failed flag (and a file lock?) that would prevent it from
getting restarted? Maybe? Or maybe this would be ok?

From Sherlock staff -
"
On Sherlock, preemption is configured to cancel and resubmit jobs. So
preempted jobs receive the regular SIGTERM signal, followed by SIGKILL. So
there's no way to distinguish between being preempted and reaching the
regular time limit from within the job, as they basically are the same
mechanism (to preempt a job, the scheduler sets its end time to the current
time, to effectively make it reach its time limit).

For your use case, you probably don't need to bother about resubmitting
preempted jobs, since that is the default behavior: the scheduler will
automatically requeue preempted jobs, unless they have been submitted with
the --no-requeue option.

Also, exit codes are typically non-zero for job failures, but preempted
jobs should have a exit code of 0.
"

**Comment by nsheff** [comment]
That's weird that they resubmit preempted jobs, I haven't seen that before. But ok -- the problem in this case wouldn't be the flag, since it's looper that catches the flag -- this is just resubmitting the job directly to slurm (it's not going through looper, so the flag is not a problem).

The potential problem is the file lock, which is handled at the one-sample level, so it's a pypiper thing. If it got cut out in the middle of a step, it will have locked that file. By default, a resubmission will just wait on that file lock and do nothing until it is (manually) removed. This isn't really what you want on this type of cluster. However, if you run it with recover mode (`-R` or `--recover`), then it will go until it hits the file lock, and restart that step automatically. So, it will work perfectly in recover mode.

But you may not want to run all your jobs in recover mode from the beginning, all the time, since that ruins some of the benefits of file lock (if you accidentally submit the same job twice, for example).

Solution: we could have a new mode called  'dynamic recover' mode. This runs in normal mode by default, but if a 'recover' flag is set, THEN it runs in recover mode. In other words, if a file lock is set, it checks for a recover flag, and then restarts only if a recover flag exists. If a dynamic recover job is pre-empted (ie it fails via a sigkill or a sigterm, not via a job failure), then it sets a recover flag. When a pre-empted job is restarted, it will recover; when a job that failed naturally is restarted, it will not. A dual-submission still succeeds.

Wow that's pretty sweet. On Sherlock (or any cluster that can pre-empt jobs) you would just always run in dynamic recover mode. Thoughts? This would be pretty easy to implement actually, and would fit sherlock's system perfectly. everything would be handled automatically.

**Comment by nsheff** [comment]
actually, even better... I can see no reason why this dynamic recover should not just be the default in any compute environment... that way if you sigterm a job manually (with ctrl+c) it requires no intervention to restart and recover.

**Comment by rcorces** [comment]
Sounds like a great idea. It would definitely fix the problem of
preemption. Jobs that are killed due to overtime would need to be handled
slightly differently as they wouldnt be automatically resubmitted. In the
case of jobs going over-time, the failed flag would still help. At least
what I'm picturing is a wrapper for looper or a looper command that checks
all failed flags are restarts any files associated with SIGTERM/SIGKILL
failed flags as these would be good candidates for restart. maybe?

**Comment by nsheff** [comment]
I've implemented the dynamic recovery in pypiper (`v0.5-rc2`), so i will close this issue now. If there's more reason for  detailing failure in flags, feel free to reopen.
