### ISSUE TITLE
Issues with looper summarize output

### ISSUE THREAD

**Issue by rcorces** [epigen/looper#141]
1) I'm getting some extra spaces in my summary.tsv file from "looper summarize". Some of this could be on the pyPiper end of the ATACseq.py pipeline but some seems to definitely be on the looper end. Specifically, I get an extra space pre-pended to the "Time" and "Success" columns. I also get an extra space pre-pended to the "Read_type" column which is generated by the pyPiper pipeline. Are these intentional?

2) The "Success" column of summary.tsv contains the date and time in the format "06-26 09:40:49". It might be more code friendly to use a hyphen or underscore instead of a space to connect the date and time ie "06-26-09:40:49".

**Comment by vreuter** [comment]
I've not dealt with `summarize` before; do you have a good feel for it @nsheff or want me to look at this?

**Comment by nsheff** [comment]
For #2 yes you're right. This is a pypiper issue. I pushed an update.

For #1. Not intentional. I'll look into it.

**Comment by nsheff** [comment]
You're right. Somehow an extra space had snuck into pypiper. It was a pypiper bug. I fixed it now, see:

https://github.com/epigen/pypiper/commit/17cfd9d446204ad22163027f24aeb47a2e623bbd

This means just running `summarize` again won't fix this, because the spaces are in your `stats.tsv` files for each output. You could fix all them all at once by running this from your results outfolder:

```
find . -name "stats.tsv" | xargs sed -i 's/\t /\t/g'
```

If you update pypiper to dev (which is now `0.5.0-rc2`) it will work in the future. So, this update will solve both issues. Thanks @rcorces
