### ISSUE TITLE
Relax requirements on config file sections

### ISSUE THREAD

**Issue by afrendeiro** [epigen/looper#17]
Right now we have a lot of config file sections that are required (even if large sections inside them are empty) simply because we didn't prepare for it to be blank.

This impacts what @nsheff mentioned recently on getting a "minimal config file", since even for a small thing with all defaults several sections would need to be present.

I guess in practice this would imply re-writing the sections that access such attributes of the config files, but could there be another way, or alternatively are there sections which are *really* required all the time that looper should throw an error?

PS: I'd add here also things like requiring genomes/transcriptomes even if not used.

**Comment by nsheff** [comment]
I don't think we should require genomes/transcriptomes.
I think we should require very little; I described what I think of as a minimal config file here:

http://looper.readthedocs.io/en/latest/define-your-project.html

```yaml
metadata:
  sample_annotation: /path/to/sample_annotation.csv
  output_dir: /path/to/output/folder
  pipelines_dir: /path/to/pipelines/repository
```

That should be it... then also required will be a `pipeline_interface` and a `protocol_mappings`, but these should be supplied by the pipelines, not by the project.

**Comment by afrendeiro** [comment]
Yes, I agree. 
One more case is the `pipeline_interface.yaml` requiring a `resources` section which when running localhost doesn't make much sense.

What's your preference?
  1. set only existing arguments to their respective values
    - this would be an error when trying to get an non--existing attribute <- the safest option
    - but in practice due to our widespread use of AttributeDict in configs will likely return a string of the Attribute name <- which is bad because errors will be hard to catch (but manageable, we just need to check every place calling these sections)
  2. collect all used attributes and set them all to either the value or None/nan, which is more explicit but requires hardcoding things there.

I could dedicate some time to this tomorrow.

**Comment by nsheff** [comment]
For the `resources` section, it's a bit less problematic because that's the pipeline author who has to do that;  pipeline authors *should* make their pipelines usable outside of localhost. Most important is for the user who defines projects to have it really easy. 

But I guess we should also implement a default resources in case the pipeline author fails to do so. 

The first option is better in my opinion. We can solve the issue by using non-default AttributeDicts. In fact, it's already like this; the default dicts are only used in pypiper. So that point is actually not correct at the moment...I think...

**Comment by afrendeiro** [comment]
Okay, it was actually much simpler than I thought.
With a few changes I've made the project config file needing only those 3 fields.

I ask your attention only to the `compute` section: without it, there is no template or running command to submit the job, so this is in a way required. I've made the default in case this section is not specified to be the localhost template (from the pipeline_dir) and the submission command "sh".
See if you agree here f869918109c5341a458f2b0b428e561a2bb1be85.

If there are no complaints I will close the issue.

@nsheff note that `output_dir` is under `paths` in the config. We probably shouldn't change this as it would break backward compatibility with every project.

**Comment by nsheff** [comment]
Well, see #12 on your last point...

And on the `compute` section -- see f3266c6d, are you on board with that idea? I will implement a localhost default, and then there will be no `compute` section even possible in project config.

**Comment by nsheff** [comment]
The issue with your current way is that it breaks down when we remove compute templates from pipeline repos, which I think is a good thing (they're env-specific and all duplicates anyway).

**Comment by afrendeiro** [comment]
Ah right, completely forgot about the idea of mirroring paths to metadata. Fine then.

Regarding the looperenv implementation I admit I haven't yet fully grasped the whole idea/features. I'd need some more time to look at the code.
If you think that'll solve it, go ahead and implement it. Or alternatively, we could wait for after the merge to add that.

**Comment by nsheff** [comment]
I will do it now. It's basically already there, and I think it's critical from a conceptual standpoint...

**Comment by nsheff** [comment]
You can give it a quick try right now, it's working; follow instructions here:
https://github.com/epigen/looperenv

**Comment by afrendeiro** [comment]
(Ignore if this is just a side-effect of changes in progress)

From what I see now, `looper:main()` calls `prj.set_compute()` only when `--compute` is passed as argument to the CLI (there's no default to this option). `prj.compute` is then used downstream by looper in two places (https://github.com/epigen/looper/blob/dev/looper/looper.py#L204 and https://github.com/epigen/looper/blob/dev/looper/looper.py#L263) without checking if it has been set.
This would be an error unless the user config has this section specified (which we are trying to make dispensible).

We therefore need a way to have `prj.set.compute()` set defaults to run in localhost. 
One way could be to have the default option of `--compute` to be something that leads to localhost.
Or do you have something else in mind that I'm missing?

A smaller issue is also what happens if the user passes `--compute` or has compute specified in the config without setting $LOOPERENV?

**Comment by nsheff** [comment]
WIth this update, it initializes `compute` to localhost, then overwrites it if specified; first by the project config, second by command-line index into looperenv. this solve the error you mention.

if you try to specify `--compute` without LOOPERENV defined, it gives you a warning and simply doesn't load it.

**Comment by nsheff** [comment]
Ok, with this, the `compute` section is now totally optional. This brings up a new point:

Do we want to allow a `compute` section *at all*? Can you imagine a scenario when you would want a project-specific compute settings? I guess so -- what if one project needs to use one queue, while another needs a different queue (or account for resources, for that matter).

So, compute should be able to me modulated by projects, but this should be discouraged since it's more efficient to paramterize it globally using looperenv.

But as is, either way will work.

**Comment by nsheff** [comment]
I've revamped this to simplify, I think I have it solved now. It is now implemented thus:

There is a default LOOPERENV file shipped with looper. If you don't specify anything, you get this. You don't have to know it exists. You may set an environment variable `$LOOPERENV` to point to a custom file, or  pass a LOOPERENV file on the command line (`--env`) to looper (highest priority). Whichever you choose, this populates a set of compute options, including a default (localhost). So, this provides simplicity (no new requirements) as well as extreme customizability.

Compute option can then be modulated at two levels (both optional; again, simplicity and flexibility):
1. By a project config `compute` section, like we currently do. If specified in a project, these compute settings will override the `default` section provided in `LOOPERENV`. So, current projects will continue to use current settings.
2. by a command-line `--compute` parameter (highest priority), which selects a new compute setting from the currently active LOOPERENV. This would, in turn, override any relevant project settings.

The one complexity is partitions; In the long run, cemm projects could change compute sections to add a partition attribute:
```
compute:
    submission_template: slurm_template.sub
    submission_command: sbatch
    partition: longq
```
But for now, I've but a hack in that defaults it to `longq` so they will work anyway. The better solution is to not use `compute` sections in projects, because that makes them un-portable; but it will still work this way if you don't plan on moving the project around. Instead, you should use looperenv; but if you don't want this complexity and are willing to sacrifice portability, that's also acceptable. (actually, it's adding some complexity too, because the looperenv way means you can elmiinate all the project config `compute` sections).

Comments?

**Comment by nsheff** [comment]
By the way, just a final word about the partition stuff... if it seems like I'm adding complexity it's because I'm the only one using this that is dealing with multiple compute environments, and it's annoying -- leading to issues like this:

https://github.com/epigen/pipelines/commit/62397cd9eee0c772e06fefa1264ce249944f9c2a

pipelines need to be as environment-agnostic as we can and pipeline-encoded submit partitions break that.

**Comment by afrendeiro** [comment]
Okay, I think this would be good.
We probably have to make a separate section about looperenv on the docs, so that everything's clear.

**Comment by afrendeiro** [comment]
Hi @nsheff!
Today two of the newest lab members successfully setup the looper/pypiper/pipelines trifecta (dev branch) in completely virgin user accounts on the CeMM cluster! :hurray:

We just noticed a few minor things that were not so clear and could probably put out other users from using the system since some of these steps are vital to get it running:
 - if possible before the merge we should review all the README.md and requirements.txt files
 - add a line indicating how to install requirements before installing
 - if possible complete docstrings for all functions (at least in looper).
Several descriptions of the looper or pypiper CLI arguments are also really hard to understand to a newcomer. We could try to make them more understandable.

Anything on the docs that you feel could use some more work? I'll try improving some of this cases if some free time tomorrow so that we're ready for the merge thursday.

**Comment by nsheff** [comment]
great.

I think we need a combined tutorial that walks you through a basic setup using all 3.
also on docs -- how about explaining how to get looper into your path?

aren't requirements installed automatically?

**Comment by afrendeiro** [comment]
Yes, I forgot that pip installs requirements automatically. One can also install directly with `python setup.py`, but as we recommend pip, I agree, we don't necessarily have to explain how to install requirements with other methods.

**Comment by afrendeiro** [comment]
This seems to be resolved, and I had already added more specific instructions on adding looper to $PATH. I'm closing the issue
