### ISSUE TITLE
Looperenv path to submission template

### ISSUE THREAD

**Issue by afrendeiro** [epigen/looper#19]
Hi @nsheff .

I think I spotted a mistake in the looperenv part.

When running looper+pypiper+pipelines + microtest in a new virtualvenvironment one get's an error that comes from a malformed path to the submission template.

```
Loading LOOPERENV: /home/afr/env/local/lib/python2.7/site-packages/looper/submit_templates/default_looperenv.yaml
{'compute': {'default': {'submission_command': 'sh', 'partition': 'longq', 'submission_template': 'localhost_template.sub'}, 'slurm_cemm': {'submission_command': 'sbatch', 'partition': 'longq', 'submission_template': 'slurm_template.sub'}, 'econ': {'submission_command': 'sbatch', 'partition': 'economy', 'submission_template': 'slurm_template.sub'}, 'local': {'submission_command': 'sh', 'submission_template': 'localhost_template.sub'}}}
Using default LOOPERENV. You may set environment variable 'LOOPERENV' to configure compute settings.
Loading compute settings: default
{'submission_command': 'sh', 'partition': 'longq', 'submission_template': '/home/afr/env/local/lib/python2.7/site-packages/looper/submit_templates/localhost_template.sub'}
{'default': {'submission_command': 'sh', 'partition': 'longq', 'submission_template': '/home/afr/env/local/lib/python2.7/site-packages/looper/submit_templates/localhost_template.sub'}, 'slurm_cemm': {'submission_command': 'sbatch', 'partition': 'longq', 'submission_template': '/home/afr/env/local/lib/python2.7/site-packages/looper/submit_templates/slurm_template.sub'}, 'econ': {'submission_command': 'sbatch', 'partition': 'economy', 'submission_template': '/home/afr/env/local/lib/python2.7/site-packages/looper/submit_templates/slurm_template.sub'}, 'local': {'submission_command': 'sh', 'submission_template': '/home/afr/env/local/lib/python2.7/site-packages/looper/submit_templates/localhost_template.sub'}}
{'submission_command': 'sh', 'partition': 'longq', 'submission_template': '/home/afr/env/local/lib/python2.7/site-packages/looper/submit_templates/localhost_template.sub'}
Updating existing key: compute
Warning: paths section in project config is deprecated. Please move all paths attributes to metadata section.
This option will be removed in future versions.
{'compare_table': 'null.csv', 'submission_subdir': 'pipelines/submission', 'merge_table': 'null.csv', 'sample_annotation': '/home/afr/env/microtest/config/microtest_annotation.csv', 'output_dir': '/home/afr/workspace/projects/microtest', 'pipelines_dir': '/home/afr/env/pipelines', 'results_subdir': 'results_pipeline'}
{'pipelines_dir': '/home/afr/env/pipelines', 'submission_subdir': 'pipelines/submission', 'results_subdir': 'results_pipeline', 'output_dir': '/home/afr/workspace/projects/microtest'}
Results subdir: /home/afr/workspace/projects/microtest/results_pipeline
Command: run
Pipeline interface config: /home/afr/env/pipelines/config/pipeline_interface.yaml
Protocol mappings config: /home/afr/env/pipelines/config/protocol_mappings.yaml
### [1 of 1] Amplicon_human     (0.00 Gb)
Pipeline: amplicon_simple.py
        SUBFILE: /home/afr/workspace/projects/microtest/pipelines/submission/Amplicon_human_amplicon_simple.sub Traceback (most recent call last):
  File "/home/afr/env/bin/looper", line 9, in <module>
    load_entry_point('looper==0.4', 'console_scripts', 'looper')()
  File "/home/afr/env/local/lib/python2.7/site-packages/looper/looper.py", line 649, in main
    run(prj, args, remaining_args)
  File "/home/afr/env/local/lib/python2.7/site-packages/looper/looper.py", line 272, in run
    remaining_args=remaining_args)
  File "/home/afr/env/local/lib/python2.7/site-packages/looper/looper.py", line 506, in cluster_submit
    with open(submit_template, 'r') as handle:
IOError: [Errno 2] No such file or directory: '/home/afr/env/local/lib/python2.7/site-packages/looper/submit_templates/templates/slurm_template.sub'
```

The path  '.../site-packages/looper/submit_templates/templates/slurm_template.sub' shoulld be ''.../site-packages/looper/submit_templates/slurm_template.sub' and I think this comes from either this function https://github.com/epigen/looper/blob/dev/looper/models.py#L286 or maybe [here](https://github.com/epigen/looper/blob/dev/looper/models.py#L358) or [here](https://github.com/epigen/looper/blob/dev/looper/models.py#L279), I can't tell.

We also encountered this two days ago but I thought we did something wrong when using looperenv and  ended using a workaround without realizing it was a bug.

**Comment by nsheff** [comment]
This is actually as intended; submission templates are now relative to looperenv; so microtest needs to change from `tempates/slurm_template.sub` to `slurm_template.sub`, or remove the compute section entirely.

The thing is, pipelines should no longer be allowed to have submission templates, it just doesn't make sense;

**Comment by afrendeiro** [comment]
Okay then, can we update everything accordingly?

**Comment by nsheff** [comment]
Yes. A few more details for posterity:

originally, we allowed the compute section in the project config to point to a submission template, which was considered relative to the pipeline. This made it so that each pipeline repository required repeating submission template files. Actually, these templates are universal, so it makes more sense to ship them with looper. As such, it doesn't make sense to have paths relative to the pipelines repository in the compute section. Instead, the compute section in the project config file is now relative to the upper environment file. Really, for most projects, the compute section should just be completely deleted because now the defaults will handle.

Going forward, project config files need to do one of two things:

First just delete the compute section. This is the easiest, and these projects will then start using the default compute, which is what they were doing anyway. The second option is to define the custom compute section for projects that really need custom compute sections. This should be the minority of projects, and this will then require you to customize a looperenv.

So I guess this introduces a little bit of non-backwards compatibility, but it's easy to fix just delete the compute section from your project config.
