### ISSUE TITLE
looper commands

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#4]
I added a summarize function to looper which is more generic and universal in the looper/dev

you run it with `looper -c config --cmd summarize`

I think we should make a positional argument (1st arg) with commands that looper can do:
- run (what looper usually does and the default if no positioanl arg given)
- clean (already implemented; wipes all resutls for the project)
- summarize (what I just implemetned)
- check (checks on running/failed status)
- other things?

You would then run looper like this:

`looper run ...`
`looper clean ...`
`looper summarize...`

**Comment by afrendeiro** [comment]
Hmm how things change Nathan :wink: 

I think what you call `clean`, should be called `destroy`, it's very easy to confuse with 
And `clean` or `fresh` should remove all flags and locks

**Comment by nsheff** [comment]
yep, no arguments there! I know you suggested this awhile ago. I resisted then but now I changed my mind.

And yes, destroy is better. (it also prompts first)

The bigger question is: should we implement this or not?

**Comment by afrendeiro** [comment]
I think we should. I'll implement this and I propose it to be added to the new "looper release" (0.4)

**Comment by afrendeiro** [comment]
Please have a look at the the last commit (02279e798e52cbb3c772de22baced1b78ba64cb7). I took the opportunity to separate the code of each command (run, summarize, destroy) into a functions called by main().

In addition, since every command requires the config file to be passed, I made that into a positional argument. This means that you no longer need to pass it as a value for "-c", but just after the options as a argument (e.g. `looper run config.yaml` or `looper summarize config.yaml`), which I think is nice. This is nonetheless merely a proposal, let me know if you still prefer `looper run -c config.yaml`.

**Comment by nsheff** [comment]
I prefer it the way you propose.

Another idea is: we could have a 'lookup table' of projects, and you could just say the project to run instead of the whole path to the config file. Probably not worth it but just a thought.
