### ISSUE TITLE
looper in path

### ISSUE THREAD

**Issue by nsheff** [epigen/looper#8]
@afrendeiro , Is installation supposed to move the `looper` file to a folder in PATH? In my experience it moves it to .local/bin/looper, but this is not by default in my path, on every system. Sometimes it is, sometimes it's not and I'm not sure why. Is this incorrect?

**Comment by afrendeiro** [comment]
This is just the default location where all Python stuff is installed. You can specify a different one during installation (http://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip). In a virtual environment, for example, the location is by default in $PATH, but in a general environment it wouldn't be reasonable for pip to install things in some folder in $PATH just because it wants to - it doesn't know what is in those folders.

**Comment by nsheff** [comment]
maybe we should add this as an FAQ?  I was confused at why I couldn't run `looper` directly and found it in that folder eventually, but it's not documented anywhere

**Comment by nsheff** [comment]
I think we should revisit this. I think just installing looper with pip should stick it into the path.

Can we just add `.local/bin` to $PATH if it's not already there?

**Comment by nsheff** [comment]
I did add this as an FAQ but I'm still wondering if there's a better way...

**Comment by afrendeiro** [comment]
I've added info to docs and the README on how to add the looper executable to the $PATH, closing.
